language: node_js
node_js:
  - "0.10"
before_script:
  - npm install connect
  - nodepath=`which node`
  - sudo $nodepath test/vendor/server.js ../../../ &
  - sleep 5
script: phantomjs test/vendor/runner.js "http://localhost/test/index.html"
notifications:
  email: false
