language: node_js
node_js:
  - "0.10"
before_script:
  - npm install connect
  - sudo node test/vendor/server.js ../../../ 8000 &
  - sleep 5
script: phantomjs test/vendor/runner.js "http://localhost:8000/test/index.html"
notifications:
  email: false
