language: node_js
node_js:
  - "0.10"
before_script:
  - npm install connect
  - nodepath=`which node`
  - phantomjspath=/home/travis/build/nowhereman/underscore.transparent/node_modules/phantomjs/lib/phantom/bin/phantomjs
  - sudo $nodepath test/vendor/server.js ../../../ &
  - sleep 5
script: $phantomjspath test/vendor/runner.js "http://localhost/test/index.html"
notifications:
  email: false
